sudo: required
addons:
  chrome: stable

language: dart
dart_task:
- dartfmt
- dartanalyzer
- test: --platform vm
- test: --platform chrome
- test: --platform firefox

dart:
#- stable
  - dev

cache:
  directories:
    - $HOME/.pub-cache