sudo: false

language: dart
dart_task:
- dartfmt
- dartanalyzer
- test: --platform vm
- test: --platform chrome
- test: --platform firefox
- test: --platform dartium
  install_dartium: true

dart:
#- stable
  - dev

cache:
  directories:
    - $HOME/.pub-cache